### ISSUE TITLE
open files in read-only mode first

### ISSUE THREAD

**Issue by at-hatran** [ivellioscolin/sublime-plugin-readonlyprotect#2]
when open sublime or open files, can you add an option that enable read-only right from start, then users have to turn it off to edit

**Comment by ivellioscolin** [comment]
Thanks for your suggestion.
I understand your request. However, adding such a feature will confuse the purpose of this plugin. The plugin always sync the read-only status in ST with the file system. If setting to read-only mode on file opening, regardless of the actual attribute of the file system, then user may get confuse: whether the read-only state is to protect the input from ST, or to protect the file modify in the file system.

My suggestion is to create another plugin which only handle the input protection from ST, not involving the file system attribute.

**Comment by at-hatran** [comment]
would you like to make the plugin base on this https://github.com/AxxL/sublime-toggle-readonly
