### ISSUE TITLE
windows vs linux tab menu

### ISSUE THREAD

**Issue by njdro** [ivellioscolin/sublime-plugin-readonlyprotect#3]
On my Linux ST3, right-click buffer-TAB>Context Menu>"ReadOnly Protect" does not exist.  It only exists from the Main Menu>Tools>Packages>"ReadOnly Protect"

(On Windows it exists on the tab menu.)

**Comment by ivellioscolin** [comment]
Hi meoso,

Which dist are you using? I'm using terminal only recently, and may install dist as yours to reproduce the issue.

**Comment by njdro** [comment]
Debian Jessie 8,
Linux 4.9.0-0.bpo.2-amd64 Debian 4.9.18-1~bpo8+1 (2017-04-10) x86_64 GNU/Linux

Sublime text build 3126

It might also be nice to have RW/RO indicator on the tab itself (similar to the circle on the tab indicating unsaved status), But i do see the text on the status-line, so this would just a be a non-necessity perk

**Comment by ivellioscolin** [comment]
Hi meoso,

You may update to v1.3.2, see if the issue goes away.

As for the status indicator on the tab, there is no simple way to add. ST extension method view.file_name() and view.name() return the name of current open file or given name if creating new one, change them equal to copy content to a newly created file. The save/unsaved status is ST built-in feature. Seems the author doesn't provide an interface to add customized symbolic indicators. I'll try to find if there exists some alternative approach. Before that, status bar is the only quick way to check RW/RO status.

**Comment by njdro** [comment]
it works!  There is no check-mark indicator on the menu item like windows, but it works. Thank you!

**Comment by ivellioscolin** [comment]
Yes, that's because to implement per-tab control, the plugin command inherits from sublime_plugin.TextCommand Class instead of sublime_plugin.ApplicationCommand. According to ST API reference, TextCommand doesn't have is_checked() method and checkbox option. However it still works on Window. I'll leave it now and will find better solution later.
