### ISSUE TITLE
Readonly protection does not work on restored windows when Sublime is restarted

### ISSUE THREAD

**Issue by basisjp** [ivellioscolin/sublime-plugin-readonlyprotect#5]
In Sublime Text 3 on both Linux (RHEL 7) and macOS (10.15), restarting Sublime will restore previously open windows.  None of the restored windows are managed properly by ReadOnlyProtect.  They do not show the correct status in the status bar at the bottom of the window, and they do not prevent files from being edited if they are currently read-only.

**Comment by ivellioscolin** [comment]
Could you describe in detail how you reproduced this issue? What's the original permission of the file before the first time it's opened in ST? Did you change any read-only property from its tab property -> "ReadOnly Protect"?

**Comment by basisjp** [comment]
Thanks for replying - hope things are warm where you are.

The problem is that when Sublime 3.2.2 starts, it appears that only the current window is functional with respect to ReadOnlyProtect.
My default was to start Sublime with the -n switch, so in that case the new window is the only one where ReadOnlyProtect works.
I tried another test, having multiple windows up with multiple tabs, each with a combination of ReadOnly and Editable files, none of which
had their protection *modified* using ReadOnlyProtect.
Quitting Sublime and restarting without the -n switch, either from the desktop icon or from the command line, causes only the window
with focus to have functional ReadOnlyProtect - the other windows show no sign of its functionality.  This happens, as stated before,
on both macOS 10.15 and RHEL 7.

**Comment by ivellioscolin** [comment]
The default mode is manual mode in which all files (view/tab/buffer in sublime) are editable. The plugin won't save last used status. Suppose you open a new file, by default it's editable or not depends on it's attributes in file system. Suppose the file is readonly/un-editable. Now change by select "editable" in ReadOnly Protect context menu of the view/tab. Now you can change the content. Do not save the modification, close sublime and reopen it, the view/tab remains readonly since the file attributes in file system is readonly, which won't be changed by ReadOnly protect.

What you are expecting is the plugin or sublime itself can save last-used view/tab/buffer readonly status. However plugin doesn't maintain the status in plugin settings, nor can change the last-used file status settings in sublime.

Sublime may need save more view status, in addition to current "remember_open_files" and "hot_exit". However it's not open source. You may submit a feature request on its forum.

**Comment by basisjp** [comment]
Perhaps I was unclear in my description.  I never use the ReadOnly Protect context menu.  I'm referring to the ability of the plugin to monitor the externally controlled file permissions.  I've attached a screen capture of a new Sublime session, started with the -n switch, which shows that the window with focus shows that the file being edited is Readonly.  The file in the lower window, the window that was restored as part of the previous editing session, shows no file permission status.  Additionally, making external changes to that file via my SCM system does not get recognized by the plugin.  The file remains uneditable in the restored window, even if it has write permissions on startup.  If I open a new window in the session and edit the same file, it responds properly and properly displays the file permission in the bottom status bar.
<img width="369" alt="Screen Shot 2021-02-22 at 9 31 03 AM" src="https://user-images.githubusercontent.com/11251463/108730439-24e72300-74f1-11eb-9686-83a8d455d060.png">

**Comment by ivellioscolin** [comment]
What protect_mode do you set in settings? By default it's manual mode and it won't monitor its attributes in file system
```
{
    // 0: Disable
    // 1: Auto, polling stat from file system
    // 2: Manual, override by selection
    "protect_mode": 2,

    // interval in milliseconds
    "polling_interval": 1000
}
```

**Comment by basisjp** [comment]
Here are my package settings - user:
{
    // 0: Disable
    // 1: Auto, polling stat from file system
    // 2: Manual, override by selection
    "protect_mode": 1,

    // interval in milliseconds
    "polling_interval": 500
}

**Comment by ivellioscolin** [comment]
And the permission of the file has issue is? Just paste the result of "ls -l <file_name>"

**Comment by basisjp** [comment]
Understand that this is not a specific file - all files loaded into the editor behave this way.  The file permissions are typically 644 when read/write, and 444 when read only.  Have you tried to reproduce the problem?

**Comment by ivellioscolin** [comment]
test.txt 444
protect_mode set to 1 so it's auto polling mode.

1. subl
No tab opened with a empty main window. 
Load test.txt into a tab, it's readonly, matches 444. 
Right click current tab, "Readonly Protect", it's shown as "Auto Mode".
Directly close the main window and goes to exp. 2.

2. subl
Last opened tab loaded, test.txt is still readonly, same as 1.
Directly close the main window and goes to exp. 3.

3. subl -n
Now 2 main window opened. One has last opened tab "test.txt", which is still readonly. Another one is a empty window, match the "-n" arg.
Close the empty window first then the other will be same as 1) or 2).
Close the non-empty window (the one with test.txt opened) then the other will be same as the initial state before 1).

However at this step, one window doesn't show expected "Readonly" in status bar. Is this the issue you concerned about?

**Comment by basisjp** [comment]
Close.  Change step 3 to "subl -n test2.txt", where test2.txt is another file with, for instance, 644 mode.  test2.txt will be in one window, correctly indicating "Editable" in the bottom status bar.  test.txt will be in the other window, and *will not* indicate "Readonly" in the bottom status bar.  Additionally, test.txt will not respond to external mode changes - ie, if you externally make it have mode 644, it will not become writable.

**Comment by ivellioscolin** [comment]
I found the plug-in only handles the current active window on plugin_load instead of all windows, which could cause the later-opened window handling incorrect.
I just push 1.3.4, see if it can resolve your issue.

**Comment by basisjp** [comment]
That appears to have fixed the problem.  Thanks for taking care of that, and thanks for making such a useful plugin in the first place.

**Comment by ivellioscolin** [comment]
Np. :smile:
